#!/usr/bin/env node
/**
 * Refetches the self-hosted typefaces into public/fonts and regenerates
 * src/ui/tokens/fonts.css. Run when the type stack in theme.css changes.
 *
 * Self-hosting is deliberate: the game must not depend on a font CDN at
 * runtime, and a flash of fallback text would break the display register the
 * whole aesthetic rests on.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { createWriteStream } from 'node:fs';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { join } from 'node:path';

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36';
const FAMILIES = [
  ['Rubik', 'wght@300;400;500;700'],
  ['Chakra+Petch', 'wght@600;700'],
  ['Saira+Condensed', 'wght@700;800'],
];
const SUBSETS = new Set(['latin', 'latin-ext']);
const OUT_DIR = 'public/fonts';

await mkdir(OUT_DIR, { recursive: true });

const faces = [];
for (const [family, axis] of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${family}:${axis}&display=swap`, {
    headers: { 'User-Agent': UA },
  });
  const css = await res.text();
  const blocks = css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g);
  for (const [, subset, body] of blocks) {
    if (!SUBSETS.has(subset)) continue;
    const name = /font-family:\s*'([^']+)'/.exec(body)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1];
    const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(body)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(body)?.[1]?.trim();
    if (!name || !weight || !url) continue;
    const file = `${name.toLowerCase().replace(/ /g, '-')}-${weight}-${subset}.woff2`;
    faces.push({ name, weight, url, range, file });
  }
}

const written = new Set();
for (const face of faces) {
  if (written.has(face.file)) continue;
  written.add(face.file);
  const res = await fetch(face.url, { headers: { 'User-Agent': UA } });
  if (!res.ok || !res.body) throw new Error(`failed to fetch ${face.file}: ${res.status}`);
  await pipeline(Readable.fromWeb(res.body), createWriteStream(join(OUT_DIR, face.file)));
}

const css = [
  '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.',
  '   Self-hosted so the game never depends on a font CDN at runtime.',
  '   Latin + Latin-Extended subsets only. */',
  '',
  ...faces.flatMap((f) => [
    '@font-face {',
    `  font-family: '${f.name}';`,
    '  font-style: normal;',
    `  font-weight: ${f.weight};`,
    '  font-display: swap;',
    `  src: url('/fonts/${f.file}') format('woff2');`,
    ...(f.range ? [`  unicode-range: ${f.range};`] : []),
    '}',
    '',
  ]),
].join('\n');

await writeFile('src/ui/tokens/fonts.css', css);
console.log(`fonts: ${written.size} files, ${faces.length} @font-face rules`);
